language: python
cache: pip

env:
  - SINGLESTATION=./locator/data/models
python:
  - "2.7"
  - "3.5"

install:
  - sudo apt-get -qqy install hdf5-tools
  - pip install -qq -r requirements.txt
  - pip install coveralls
  - wget -q https://polybox.ethz.ch/index.php/s/mtF15vrUY53XCcj/download -O $HOME/105models.tar.bz2
  - tar -xf $HOME/105models.tar.bz2 -C locator/data/models/data/bodywave/
  - ln -s sstaehler/locator $HOME/locator

script:
  # Create test file
  - python ./locator/tools/create_test.py 41 70 --travis
  - coverage run main.py locator_input.yml locator_test_41_70.yml --plot
  #- python locator/test_h5_output.py locator_output_18-12-31T2359.h5 locator/data/tests/MQS.h5 -p 0.001
  #- ls
  #- cat locator/data/locator_input_20190719.yaml | ./locator.bash
  # - python locator/test_h5_output.py locator_output_19-07-19T1333.h5 locator/data/tests/locator_output_ref_190719.h5 -p 1e-5

after_success:
  - cd $TRAVIS_BUILD_DIR; coveralls
  - codecov
