language: python
env:
  - SINGLESTATION=./locator/data/models
python:
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - sudo apt-get -qqy install hdf5-tools
  - pip install -qq -r requirements.txt
# command to run tests
script:
  - python main.py locator/data/locator_input.yaml locator/data/locator_output.yaml --plot
