language: python
cache: pip
  directories:
    $HOME/250models.tar.bz2

env:
  - SINGLESTATION=./locator/data/models
python:
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - sudo apt-get -qqy install hdf5-tools
  - pip install -qq -r requirements.txt
  - pip install coveralls
  - wget -q https://polybox.ethz.ch/index.php/s/ibufo2dYhyUfu6j/download -O $HOME/250models.tar.bz2
  - tar -xf $HOME/250models.tar.bz2 -C locator/data/models/data/bodywave/

# command to run tests
script:
  #- coverage run main.py locator/data/locator_input.yaml locator/data/locator_output.yaml --plot
  - cat locator/data/locator_input.yaml | locator.bash
  - python locator/test_h5_output.py locator_output_19-01-03T1500.h5 locator/data/tests/locator_output_ref.h5 -p 1e-5
  - cat locator/data/locator_input_20190719.yaml | locator.bash
  - python locator/test_h5_output.py locator_output_19-07-19T1333.h5 locator/data/tests/locator_output_ref_190719.h5 -p 1e-5

after_success:
  - cd $TRAVIS_BUILD_DIR; coveralls
